export const PAGE_KEYS = Object.freeze({
  landing: 'landing',
  passwordReset: 'passwordReset',
  error: 'error',
  signUp: 'signUp',
  signIn: 'signIn',
  forgotPassword: 'forgotPassword',
  myProtocols: 'myProtocols',
  profile: 'profile',
  idProof: 'idProof',
  settings: 'settings',
  dispatchers: 'dispatchers',
  editDispatcher: 'editDispatcher',
  newDispatcher: 'newDispatcher',
  drivers: 'drivers',
  editDriver: 'editDriver',
  newDriver: 'newDriver',
  admins: 'admins',
  editAdmin: 'editAdmin',
  newAdmin: 'newAdmin',
  customers: 'customers',
  editCustomer: 'editCustomer',
  customerPriceList: 'customerPriceList',
  newCustomer: 'newCustomer',
  employees: 'employees',
  editEmployee: 'editEmployee',
  newEmployee: 'newEmployee',
  orderEntries: 'orderEntries',
  editOrderEntry: 'editOrderEntry',
  newOrderEntries: 'newOrderEntries',
  orderEntryProtocols: 'orderEntryProtocols',
  orderEntryProtocol: 'orderEntryProtocol',
  drivingServices: 'drivingServices',
  tourManagement: 'tourManagement',
  tourDetails: 'tourDetails',
  activeTours: 'activeTours',
  acceptedTours: 'acceptedTours',
  finishedTours: 'finishedTours',
  completedTours: 'completedTours',
  cancelledTours: 'cancelledTours',
  notAcceptedTours: 'notAcceptedTours',
  notAssignedTours: 'notAssignedTours',
  newAssignedTours: 'newAssignedTours',
  newTour: 'newTour',
  startTour: 'startTour',
  protocolTakeover: 'protocolTakeover',
  availability: 'availability',
});

export const PAGE_TITLES_KEYS = Object.freeze({
  [PAGE_KEYS.landing]: 'Transfery',
  [PAGE_KEYS.passwordReset]: 'Reset password',
  [PAGE_KEYS.error]: 'Error',
  [PAGE_KEYS.signUp]: 'Sign Up',
  [PAGE_KEYS.signIn]: 'Sign In',
  [PAGE_KEYS.forgotPassword]: 'Forgot password?',
  [PAGE_KEYS.myProtocols]: 'My protocols',
  [PAGE_KEYS.profile]: 'Profile',
  [PAGE_KEYS.idProof]: 'Proof your ID',
  [PAGE_KEYS.settings]: 'Settings',
  [PAGE_KEYS.dispatchers]: 'Dispatchers list',
  [PAGE_KEYS.editDispatcher]: 'Edit dispatcher',
  [PAGE_KEYS.newDispatcher]: 'Add new dispatcher',
  [PAGE_KEYS.drivers]: 'Drivers list',
  [PAGE_KEYS.editDriver]: 'Edit driver',
  [PAGE_KEYS.newDriver]: 'Add new driver',
  [PAGE_KEYS.admins]: 'Admins list',
  [PAGE_KEYS.editAdmin]: 'Edit admin',
  [PAGE_KEYS.newAdmin]: 'Add new admin',
  [PAGE_KEYS.customers]: 'Customers list',
  [PAGE_KEYS.editCustomer]: 'Edit-customer',
  [PAGE_KEYS.customerPriceList]: 'Customer price list',
  [PAGE_KEYS.newCustomer]: 'Add new customer',
  [PAGE_KEYS.employees]: 'Employees list',
  [PAGE_KEYS.editEmployee]: 'Edit-employee',
  [PAGE_KEYS.newEmployee]: 'Add new employee',
  [PAGE_KEYS.orderEntries]: 'Order entries list',
  [PAGE_KEYS.editOrderEntry]: 'Edit order entry',
  [PAGE_KEYS.newOrderEntries]: 'New order entry',
  [PAGE_KEYS.orderEntryProtocols]: 'Order entry protocols',
  [PAGE_KEYS.orderEntryProtocol]: 'Order entry protocol preview',
  [PAGE_KEYS.drivingServices]: 'Driving services',
  [PAGE_KEYS.tourManagement]: 'Tours list',
  [PAGE_KEYS.tourDetails]: 'Tour details',
  [PAGE_KEYS.newAssignedTours]: 'New assigned tours',
  [PAGE_KEYS.notAssignedTours]: 'Not assigned tours',
  [PAGE_KEYS.finishedTours]: 'Finished tours',
  [PAGE_KEYS.activeTours]: 'Active tours',
  [PAGE_KEYS.acceptedTours]: 'Accepted tours',
  [PAGE_KEYS.completedTours]: 'Completed tours',
  [PAGE_KEYS.notAcceptedTours]: 'Not accepted tours',
  [PAGE_KEYS.cancelledTours]: 'Cancelled tours',
  [PAGE_KEYS.startTour]: 'Start tour',
  [PAGE_KEYS.newTour]: 'New tour',
  [PAGE_KEYS.protocolTakeover]: 'Protocol takeover',
  [PAGE_KEYS.availability]: 'Calendar',
});

export const ROUTES= Object.freeze({
  [PAGE_KEYS.landing]: '/',
  [PAGE_KEYS.passwordReset]: '/password-reset',
  [PAGE_KEYS.error]: '*',
  [PAGE_KEYS.signUp]: '/sign-up',
  [PAGE_KEYS.signIn]: '/sign-in',
  [PAGE_KEYS.forgotPassword]: '/forgot-password',
  [PAGE_KEYS.myProtocols]: '/my-protocols',

  [PAGE_KEYS.profile]: '/profile',
  [PAGE_KEYS.settings]: '/settings',

  [PAGE_KEYS.dispatchers]: '/dispatchers',
  [PAGE_KEYS.editDispatcher]: '/edit-dispatcher/:id',
  [PAGE_KEYS.newDispatcher]: '/new-dispatcher',

  [PAGE_KEYS.drivers]: '/drivers',
  [PAGE_KEYS.editDriver]: '/edit-driver/:id',
  [PAGE_KEYS.newDriver]: '/new-driver',
  [PAGE_KEYS.protocolTakeover]: '/protocol-takeover',
  [PAGE_KEYS.availability]: '/driver-availability',
  [PAGE_KEYS.idProof]: '/id-proof',

  [PAGE_KEYS.admins]: '/admins',
  [PAGE_KEYS.editAdmin]: '/edit-admin/:id',
  [PAGE_KEYS.newAdmin]: '/new-admin',

  [PAGE_KEYS.customers]: '/customers',
  [PAGE_KEYS.editCustomer]: '/edit-customer/:id',
  [PAGE_KEYS.customerPriceList]: '/customer/:id/price-list',
  [PAGE_KEYS.newCustomer]: '/new-customer',

  [PAGE_KEYS.employees]: '/employees',
  [PAGE_KEYS.editEmployee]: '/edit-employee/:id',
  [PAGE_KEYS.newEmployee]: '/new-employee',

  [PAGE_KEYS.orderEntries]: '/order-entries',
  [PAGE_KEYS.editOrderEntry]: '/edit-order-entry/:id',
  [PAGE_KEYS.newOrderEntries]: '/new-order-entry',
  [PAGE_KEYS.orderEntryProtocols]: '/order-entry/protocols',
  [PAGE_KEYS.orderEntryProtocol]: '/order-entry/protocol/:id',
  [PAGE_KEYS.drivingServices]: '/driving-services',

  [PAGE_KEYS.tourManagement]: '/tour-management',
  [PAGE_KEYS.tourDetails]: '/tour-details',
  [PAGE_KEYS.startTour]: '/start-tour',
  [PAGE_KEYS.activeTours]: '/tour-management/active',
  [PAGE_KEYS.acceptedTours]: '/tour-management/accepted',
  [PAGE_KEYS.finishedTours]: '/tour-management/finished',
  [PAGE_KEYS.completedTours]: '/tour-management/completed',
  [PAGE_KEYS.cancelledTours]: '/tour-management/cancelled',
  [PAGE_KEYS.newAssignedTours]: '/tour-management/new-assigned',      // NEW
  [PAGE_KEYS.notAssignedTours]: '/tour-management/not-assigned',      // NOT
  [PAGE_KEYS.notAcceptedTours]: '/tour-management/not-accepted',
  [PAGE_KEYS.newTour]: '/tour-management/new-tour',
});
