export enum TitleCodes {
  CORPORATE_PARTNERS = 'CORPORATE_PARTNERS_BLOCK',
  HOW_IT_WORKS = 'HOW_IT_WORKS_BLOCK',
  PRICE = 'PRICE_BLOCK',
  CUSTOMER_REVIEWS = 'CUSTOMER_REVIEWS',
  HELP_BLOCK = 'HELP_BLOCK',
}
