name: BE unit test
run-name: ${{ github.actor }} is testing BE
on:
    push:
      branches: [ master ]
      paths: 
          - BE/**
    pull_request:
      branches: [ master ]
      paths: 
          - BE/**
jobs:
  run-defined-unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./BE
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm ci
      
      - run: npm run test