name: Run E2E
on:
  push:
    branches: [ master ]
    paths: 
      - FE/**
  pull_request:
    branches: [ master ]
    paths: 
      - FE/**
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
      working-directory: FE
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      working-directory: FE
    - name: Run Playwright tests
      run: npx playwright test
      working-directory: FE
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: FE/playwright-report/
        retention-days: 7